name: Build and (if master) sync to S3

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: bahmutov/npm-install@v1
    - name: Install purgecss
      run: npm install purgecss
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: build jekyll 
      run: bundle exec jekyll build
    - name: pandoc
      run: bundle exec ruby _pandoc/pandoc.rb
    - name: purgecss 
      run: make purge
  deploy:
    if: github.ref == 'master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: speedshop-dotcom
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: '_site'   